### ISSUE TITLE
74AHCT1G125DBV replacement?

### ISSUE THREAD

**Issue by hedefalk** [Ttreintaysiete/ardcore#1]
Hi, I'm trying to source parts on a shoestring for a couple of units of this. I'm trying to avoid mouser and similar because of shipping. The only thing that was a bit problematic is the 74AHCT1G125DBV. It's not easily available on the surplus sources I'm using (mostly just aliexpress and ebay). Seems like the SOT-353 package is a lot easier to get cheap:

https://www.aliexpress.com/item/Free-Shipping-50PCS-lot-74AHCT1G125SE-7-IC-BUS-BUFF-3ST-SGL-N-INV-SOT353-125-74AHCT1G125/32682004541.html?spm=2114.search0104.3.2.CX6wXz&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10065_10151_10344_10068_10345_10342_10343_10340_10341_10171_10541_10084_10083_10307_10301_5640015_10303_10060_10155_10154_10056_10055_10539_10538_5370015_10537_10312_10536_10059_10313_10314_10534_10533_100031_10103_10073_10102_10142_10107,searchweb201603_1,ppcSwitch_5&btsid=7003e7aa-5e92-4a2a-a64d-ae9a055d2782&algo_expid=900eb61a-5ea6-4e61-8745-6672c314c970-0&algo_pvid=900eb61a-5ea6-4e61-8745-6672c314c970

74AHCT1G125DBV is SOT23-5

Maybe for the next iteration :) Do you happen to know if there are any other replacements?

Thanks a lot for this work!

**Comment by beeva-luisgonzalez** [comment]
Hi!
first of all thanks a lot for your message and taking time for the suggestion. This is the Mouser BOM ill be adding to the doc:

https://www.mouser.es/ProjectManager/ProjectDetail.aspx?AccessID=9c269e6775

I totally agree with all your arguments, but we wanted to make this project easy to build for anyone regardless its DIY level, so having a single "no brainer" mouser cart is the best for most cases...

Mouser is free shipping when you purchase 50€ or more which seems reasonable as your probably know, but we will consider changing this if we find a similar part in SOT-353 that is compatible.

We are using this part mainly because we copied (and trust) Mutable Instruments designs.. since Oliver uses this on most its designs.

**Comment by hadesbox** [comment]
and please let us know how your build went... if you have any suggestions for the board or anything else... we tried to make it super easy to build silkscreen was carefully placed, all components have enough (we hope) space etc...

**Comment by hedefalk** [comment]
Will do!

**Comment by hedefalk** [comment]
I'll close the issue so it doesn't look like you're having a bug :)

**Comment by hedefalk** [comment]
Just one more thing when I have you on the line :)

You recommend the AVRPISP mk2, is there a reason I can't just use an arduino as ISP, like instructions here https://www.arduino.cc/en/Tutorial/ArduinoISP

**Comment by hadesbox** [comment]
@hedefalk ArduinoISP will work just fine! Its just a bit slower and if you plan to do some serious programming its better to us AVRISP mk2, but otherwise using a second arduino as programmer is fine... I'll add your link to the "programming" section as an alternative!

**Comment by hadesbox** [comment]
Ohh one thing you need to test is how to change the fuses of the atmega328 because by default it has the fuses to use its internal oscillator, I added to the building doc how to do it with avrispmkii and avrdude, dont know how to do it with ArduinoISP solution... should work!

**Comment by hedefalk** [comment]
Great, thanks!
