### ISSUE TITLE
Placement exact between panel and component pcb?

### ISSUE THREAD

**Issue by hedefalk** [Ttreintaysiete/ardcore#4]
Got my PCB's from China the other day (yey!) and started on a front panel. I'm 3d printing and designing in openscad. I couldn't find a decent ruler so I extracted the values from the panel eagle file here. I noticed that the LED's are a bit displaced. My OCD wants to fix this, in your experience, would there be any problem in aligning them perfectly with the jacks and just bending in place? Should be fine right?

The other issue is that also the jacks a tiny amount misplaced too as seen here:

![image](https://user-images.githubusercontent.com/116520/34457859-b70a7754-edbe-11e7-8e83-6e0962b0bdcf.png)

I guess they are on the PCB too, that you used the same positions? I have my caliper and good rulers at work so I'm eyeballing…

Need to reinforce with extra plastic inbetween the thonkiconns or the panel isn't stiff enough and bends so I really need all the room I can get…

One more piece of feedback/question - the front side 10uF electrolytic - the ones I have stocked have a taller footprint than the thonkiconns so needed to bend it in place. Did you use smaller caps?

Thanks a lot for sharing this pcb <3

**Comment by hadesbox** [comment]
Hi @hedefalk you are totally right on everything, the hole are misplaced (I'm very sorry for this... :( ) on both pcb and panel, I will fix this on next board revision.. but your boards and panels will work anyway because all the tests we have done fit perfectly regardless of the small miss align since we used the same __misaligned__ coordinates on both.

Regarding the 10uF cap, if you use the value listed on the [BOM](https://github.com/Ttreintaysiete/ardcore/blob/master/BUILDING.md), you should not have a problem is a short lengthed cap so no bending is needed. The part is [this and its 5mm of length](https://www.mouser.es/productdetail/panasonic/ece-a1vks100?qs=sGAEpiMZZMtZ1n0r9vR22ZGaUoI0JcRfQi0J%252bD7I9js%3D) .

**Comment by hadesbox** [comment]
Check the images I posted here https://imgur.com/gallery/Asrzm so you can see the 10u caps I'm using. I decided to use 10u throughhole caps because they are easy to solder than the 10u caps. The big 47u caps are not super difficult to solder so I left them SMD since I couldn't find a short 47u through hole.

I know it doesn't look like its very standard to put caps on different packages but I took as a philosophy to make this as easy to build (and to prevent as much errors/bridges) as possible, to make this 0603 smd board as friendly as possible.

**Comment by hadesbox** [comment]
BTW if you want to share your panel please consider making a pull request as the one I designed is super simple and ugly.

**Comment by hedefalk** [comment]
@hadesbox Ah, right, I didn't actually use the BOM as a shopping cart come to think of it :) The electrolytics I had was taller, but they fitted if I bent them.

I'm only half way through with my first Ardcore and currently away from all my stuff until 8 jan. I'll test the panel design thoroughly and then I can PR it as an STL or put up on thingiverse if you want. It's just a basic 3d print though, no markings or anything. I typically sand the front, spray paint black and hand paint the markings, white really no fancy stuff.

I'm considering getting screen printing gear. I'm really into white on black like old Moog's but I don't like the PCB panels much.
